title: Shashank Chunduru
logo: /assets/img/IMG_0474.png
description: Solution Architect at Estee Lauder Companies and Data Science Student
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
