title: Shashank Chunduru
logo: /assets/img/logo.png
description: Solution Architect at Estee Lauder Companies and Data Science Student
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
